### ISSUE TITLE
Adicionar a conveção de commits no Gui de Contribuiçao

### ISSUE THREAD

**Issue by kaykesandes** [elidianaandrade/dio-lab-open-source#107]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização de commits

**Descreva as alternativas que você considerou**
Inserir meu readme

**Contexto adicional**
N/A

**Comment by kaykesandes** [comment]
Desejo colocar meu readme.md para conclusão do bootcamp

**Comment by elidianaandrade** [comment]
Olá Kayke! Para adicionar seu profile README, basta seguir as [instruções](https://github.com/elidianaandrade/dio-lab-open-source) presentes no README do repositório, o passo a passo é demonstrado no lab e a solicitação é feita na aba "Pull Requests". 

Abraço e bons estudos 🤗
