### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de commits no Guia de Contribuição

### ISSUE THREAD

**Issue by Shoiti22** [elidianaandrade/dio-lab-open-source#1366]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Adicionar Informações referente a padronização das mensagens dos commits no guia de contribuição

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de commits.

**Contexto adicional**
N/A

**Comment by alexandresouza9** [comment]
https://desktop.github.com/
