### ISSUE TITLE
[SUGESTÃO]

### ISSUE THREAD

**Issue by iurynovarino** [elidianaandrade/dio-lab-open-source#227]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Notei que em nenhum momento do curso foi mencionado o GITHub Desktop.

**Descreva a solução que você gostaria**
O Github Desktop é um software de simples utilização, facilitaria muito quem está começando, pois a ferramenta é bem intuitiva.
- Poderia ser criada uma nova vídeo aula sobre o assunto na plataforma DIO;
- Criação de um resumo escrito sobre a utilização dessa plataforma.

**Descreva as alternativas que você considerou**
Caso seja necessário posso encaminhar um artigo sobre a utilização dessa ferramenta.

**Contexto adicional**
O site oficial da ferramenta é https://desktop.github.com/

**Comment by elidianaandrade** [comment]
Olá, Iury! O GitHub Desktop é citado em "Para saber mais" no curso "Versionamento de Código com Git e GitHub", pois devido a limitação de tempo tendo em vista um curso inserido num Bootcamp, não é possível abordar detalhadamente os GUI Clients, algo que se encaixaria melhor no contexto de uma Formação. Nesse caso sugiro contatar diretamente na plataforma para que isso possivelmente venha como demanda para algum instrutor.
 Abraço e bons estudos 🤗

![versionamento-de-codigo-com-git-e-github](https://github.com/elidianaandrade/dio-lab-open-source/assets/97471199/e9aa08b9-a8a1-41f0-9da6-04e8f6362791)
