### ISSUE TITLE
[SUGESTÃO]explicação de termos do git e github

### ISSUE THREAD

**Issue by Beatriz-Lim** [elidianaandrade/dio-lab-open-source#301]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
não

**Descreva a solução que você gostaria**
Que não seja mostrado apenas o uso das aplicações mais também o que elas significam.

**Descreva as alternativas que você considerou**
Os comando são todos em inglês, o interessante seria que o curso trouxesse a tradução e não só isso, mais também o seu significado dentro daquela aplicação.

**Contexto adicional**
Para um iniciante em programação e sem conhecimento em inglês, fica difícil lidar com tantos termos. Acredito que com o tempo e pratica esses conceitos fiquem naturais, mas para primeiro momento seria interessante dar maior significado aos termos usados em aulas.

**Comment by elidianaandrade** [comment]
Oii, Beatriz! Isso é abordado no curso "Versionamento de Código com Git e GitHub" , que antecede esse lab. Nele é abordado tanto o significado quanto a função de cada comando (que nesse lab é revisada), mostrando tanto na teoria quanto na prática. Você também pode usar o tradutor como ferramenta de estudos, infelizmente tendo em vista a duração de um lab não é possível retomar tudo que já foi abordado, pois é uma proposta mais prática com algumas revisões e por isso é posicionado após o curso introdutório. 
Qualquer dúvida pode me contatar por aqui ou pelo LinkedIn. Abraço bons estudos 🤗

![image](https://github.com/elidianaandrade/dio-lab-open-source/assets/97471199/e4cbb1aa-b10a-4fcc-85ec-83d497241add)
![image](https://github.com/elidianaandrade/dio-lab-open-source/assets/97471199/2dad8b7e-dcad-4955-a3f9-7964c1adb561)
