### ISSUE TITLE
[SUGESTÃO] Adicionar o link de Discord nos Badges

### ISSUE THREAD

**Issue by area-41** [elidianaandrade/dio-lab-open-source#342]
Minha sugestão é para adicionar o badge do Discord às opções da pasta utils.
Acredito que na comunidade há várias pessoas que utilizam esta ferramenta e que isso possa ser útil aqueles que quiserem deixar o seu link do Discord.

**Comment by totorourbem** [comment]
Eu pensei nisso na hora de fazer meu profile, e dei uma lida por ai. 
Não é possível criar um link direto para o seu usuário específico no Discord usando apenas uma badge em Markdown. A badge do Discord que é comumente utilizada em Markdown é vinculada a um servidor ou comunidade específica no Discord.
]
Se for esse o caso, seria pra adicionar isso?

`[![Discord](https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white)](link_do_convite_do_servidor)
`

**Comment by area-41** [comment]
Sim, seria isso apenas. Desculpa se é  muito simples, sou novo ainda nessas
coisas. Rs

Em sex, 7 de jul de 2023 17:06, Ricardo Jeferson da Silva Francisco <
***@***.***> escreveu:

**Comment by totorourbem** [comment]
Sem problemas, eu também tô começando.

Só fiquei na dúvida serra pra servidor ou pra user (o que é uma pena, porque o discord é a única que passa pelo proxy do meu trampo)
Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
