### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de Commits no Guia de Contribuição

### ISSUE THREAD

**Issue by ThalisonAmaral2** [elidianaandrade/dio-lab-open-source#3443]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Adicionar informações referentes a padraonização das menagens dos commits no Guia de Contribuição.

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de commits e uma descrição a respeito do seu uso.

**Contexto adicional**
N/A

**Comment by BEFEFG** [comment]
Boa sugestão
