### ISSUE TITLE
[SUGESTÃO] Ter Módulos ainda mais Específicos de Git

### ISSUE THREAD

**Issue by Jean-Carlos-Tavares-Dev** [elidianaandrade/dio-lab-open-source#37]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Gostaria de que as aulas de git fosse mais constantes que é muito útiioç;
**Descreva as alternativas que você considerou**
Ter modulos ainda mais especificos de git. 
**Contexto adicional**
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by elidianaandrade** [comment]
Olá, Jean! Obrigada pela sugestão!

Sobre o curso atual, a demanda foi explicar Git e GitHub considerando sobretudo alguém que está tendo um primeiro contato. Busquei ir um pouco além do requisitado tentando me manter dentro da média de tempo considerando um curso inserido num Bootcamp, então existem outros pontos para explorar principalmente dentro da temática desse lab.

Dentro da plataforma tem cursos de outros instrutores sobre o mesmo tema, mas ainda não conta com uma formação específica, sugiro solicitar diretamente na plataforma para quem sabe essa demanda chegar para mim ou outro instrutor da DIO.

Abraço e bons estudos! 🤗
