### ISSUE TITLE
[SUGESTÃO]Comandos do SHELL

### ISSUE THREAD

**Issue by Belletati** [elidianaandrade/dio-lab-open-source#421]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar uma tabela com os principais comandos do SHELL para facilitar a utilização do terminal.

**Descreva as alternativas que você considerou**
Adicionar uma tabela com os comandos utilizados nas aulas de Git/Github.

**Contexto adicional**
Aulas incríveis Eli, parabéns e obrigada!

**Comment by elidianaandrade** [comment]
Obrigada, Juliana! Fico muito feliz e lisonjeada ☺️

 Agradeço a sugestão! Eu quero atualizar o outro repositório [dio-curso-git-github](https://github.com/elidianaandrade/dio-curso-git-github) com mais comandos, pois esse aqui estou deixando mais aberto para a prática da comunidade e o outro é referente ao curso introdutório. Por enquanto estou com tempo apertado, mas assim que eu puder já incluo nele. Até lá, indico o vídeo que meu noivo gravou [Git Bash Descomplicado: Comandos Essenciais para Navegar no Terminal](https://youtu.be/ZQx7o9TMVVU) que está lá no nosso canal e trás uma lista de comandos.

[https://youtu.be/ZQx7o9TMVVU](https://youtu.be/ZQx7o9TMVVU)

Agradeço o feedback! Abraço e bons estudos ☺️💕

**Comment by elidianaandrade** [comment]
Obrigada, Juliana! Fico muito feliz e lisonjeada ☺️

Agradeço a sugestão! Eu quero atualizar o outro repositório [dio-curso-git-github](https://github.com/elidianaandrade/dio-curso-git-github) com mais comandos, pois esse aqui estou deixando mais aberto para a prática da comunidade e o outro é referente ao curso introdutório. Por enquanto estou com tempo apertado, mas assim que eu puder já incluo nele. Até lá, indico o vídeo que meu noivo gravou [Git Bash Descomplicado: Comandos Essenciais para Navegar no Terminal](https://youtu.be/ZQx7o9TMVVU) que está lá no nosso canal e traz uma lista de comandos.

https://youtu.be/ZQx7o9TMVVU

Agradeço o feedback! Abraço e bons estudos ☺️💕
