### ISSUE TITLE
[SUGESTÃO] Adicionar convenção de commits no guia de Contribuição.

### ISSUE THREAD

**Issue by carlosvl11** [elidianaandrade/dio-lab-open-source#4450]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização das mensagens dos commits no [Guia de Contribuição]
 (https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md).

**Descreva as alternativas que você considerou**
Inserir uma tabela demostrando os tipos de commits e uma descrição a respeito do seu uso.

**Contexto adicional**
N/A.

**Comment by voaneves** [comment]
Boa ideia, @carlosvl11!

**Comment by carlosvl11** [comment]
Obrigado pela colaboração
