### ISSUE TITLE
[SUGESTÃO] Quanto mas exemplos e explicações sobre o github, melhor! 😁

### ISSUE THREAD

**Issue by wladimith** [elidianaandrade/dio-lab-open-source#49]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
As aulas disponíveis são bastante esclarecedoras, mas confesso que gostaria de mais conteúdos específicos sobre o trabalho com o repositório local do GitHub.

**Descreva as alternativas que você considerou**
N/A.

**Contexto adicional**
N/A.

**Comment by Brumelo85** [comment]
Concordo. Excelente material, mais seria mais preciso aprender mais sobre o Github e através dele já praticar mais.

**Comment by elidianaandrade** [comment]
Oii, agradeço a sugestão! Como comentei na Issue #37 a demanda foi explicar Git e GitHub levando em conta quem está tendo um primeiro contato, e por se tratar de um curso inserido em um Bootcamp acaba sendo necessário sintetizar para não ultrapassar o limite de tempo. 

Conteúdos mais específicos se enquadrariam num contexto de uma Formação, até o momento a plataforma não contém, mas possui outros cursos de Git. Sugiro solicitarem na plataforma, para quem sabe isso vim como uma demanda para um instrutor.

Abraço para vocês e bons estudos! 🤗🤗
