### ISSUE TITLE
[SUGESTÃO] - Adicionar a imagem/ desenho na convenção de commits no guia de contribuição

### ISSUE THREAD

**Issue by KellyPLSilva** [elidianaandrade/dio-lab-open-source#4963]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Uma descrição clara e concisa de qual é o problema.

**Descreva a solução que você gostaria**
Adicionar  imagem na frente das palavras: 1.feat, 2.fix, 3.docs, 4.style, 5.refactor, 6.test
**1 :sparkles:  
   2 :boom:   
   3 :books: 
   4 :ok_hand:  
   5 :recycle: 
   6 :white_check_mark:**

**Descreva as alternativas que você considerou**
Um README com imagens é crucial, para Clareza Visual, Atração de Imagens atraem leitores, tornando o projeto mais envolvente.
Instrução Eficaz : Guia os usuários nas configurações e uso correto do projeto
Contexto Rápido e Engajamento, imagens cativam e gostavam do interesse dos leitores. 

**Contexto adicional**
Adicione qualquer outro contexto ou captura de tela sobre a solicitação de recurso aqui.

**Comment by BelisnalvaCosta** [comment]
Olá KellyPLSilva, ótima sugestão, pois atualmente as empresa têm aberto oportunidades para as pessoas que têm algum tipo de deficiência e na minha sugestão seria também incluir áudios ao lado das figuras ou icons.
