### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no Guia de Contribuição

### ISSUE THREAD

**Issue by stefanylins** [elidianaandrade/dio-lab-open-source#5698]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização das mensagens dos commits no Guia de Contribuição.

**Descreva as alternativas que você considerou**
Inserir um tabela demonstrando os tipos de commits e uma descrição a respeito do seu uso.

**Contexto adicional**
N/A.

**Comment by caioandrade42** [comment]
Boa noite @stefanylins já existe uma tabela com referências para a padronização de commits no Guia de Contruição, como pode ser verificado através do link abaixo.
https://github.com/elidianaandrade/dio-lab-open-source/blob/d08848f408a077d8d905507aa88487c8432919cd/CONTRIBUTING.md
