### ISSUE TITLE
[SUGESTÃO] Adicionar links das aulas na DIO

### ISSUE THREAD

**Issue by simone-alcala** [elidianaandrade/dio-lab-open-source#60]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Facilitar a localização das aulas

**Descreva as alternativas que você considerou**
Disponibilizar os links das aulas seguindo uma sugestão de ordem de estudos

**Contexto adicional**
N/A

**Comment by elidianaandrade** [comment]
Olá, Simone! Sua sugestão é referente ao lab ou a plataforma da DIO em si? Caso seja sobre a plataforma aconselho enviar por um canal oficial. Abraço e bons estudos 🤗
