### ISSUE TITLE
[SUGESTÃO] Como publicar um website nosso, e partilhar o link de forma a ser visto por todos publicamente

### ISSUE THREAD

**Issue by MiguelDFM** [elidianaandrade/dio-lab-open-source#61]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Fazer um vídeo, ou até mesmo uma live, sobre como publicar os nossos sites online 

**Descreva as alternativas que você considerou**
Através de aulas, lives , ou até mesmo por artigos.

**Contexto adicional**
Por exemplo eu criei um simples website  e ele só sai para mim, mas se alguém quiser ver ele publicamente dá sempre erro, até para mim dá se quiser consultar pelo telemóvel, só consigo mesmo por computador,  então seria bom explicar para além das várias funcionalidades que tem o GitHub, mostrar algo fundamental, como publicar um trabalho nosso , e aparecer para todos publicamente, e não somente os códigos. Obrigado

**Comment by elidianaandrade** [comment]
Olá, Miguel! Obrigada pela colaboração! Sugestões como essa aconselho que envie em algum canal oficial da DIO para que a plataforma entenda como uma demanda. Abraço e bons estudos 🤗
