### ISSUE TITLE
[SUGESTÃO] Adicionar Guia de Contribuição na conversão de commits

### ISSUE THREAD

**Issue by w0t3x** [elidianaandrade/dio-lab-open-source#6378]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**
Adicionar padronização das mensagens dos commits no [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md) referentes as informações.

**Descreva as alternativas que você considerou**
Inserir demonstração em tabela dos tipos de commits e descrição do uso.

**Contexto adicional**
NULO.

**Comment by jonhlenocosta2022** [comment]
commits diversificados
