### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no Guia de contribuição

### ISSUE THREAD

**Issue by Fabiano-Thimotheo** [elidianaandrade/dio-lab-open-source#80]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Adicionar a convenção de commits no Guia de contribuição

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de Commit e uma descrição à respeito do seu uso

**Contexto adicional**
N/A

**Comment by xxtslxx** [comment]
Muito bom!
