### ISSUE TITLE
[SUGESTÃO] Adicionar a convenção de commits no guia de contribuição

### ISSUE THREAD

**Issue by oMarcook** [elidianaandrade/dio-lab-open-source#9111]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não

**Descreva a solução que você gostaria**
Adicionar informações referentes a padronização de mensagens dos commits no Guia de Contribuição.

**Descreva as alternativas que você considerou**
Inserir uma tabela demonstrando os tipos de commits e uma descrição a respeito do seu uso

**Contexto adicional**
N/A

**Comment by ssantos89** [comment]
Obrigado pela colaboração! É uma boa sugestão, vou adicioná-la ao Guia.
